version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=golden
      - POSTGRES_PASSWORD=pass1234
    ports:
      - '5432:5432'
    volumes:
      - golden_db:/var/lib/postgresql/data
volumes:
  golden_db:
    driver: local
