import Head from 'next/head';
import Layout from '../components/layout';
import { AppProvider } from '../context/appContext';

export default function Home() {
  return (
    <AppProvider>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Layout>
            <div>
              <h1 className="text-3xl font-bold underline">Hello world!</h1>
            </div>
          </Layout>
        </main>
      </>
    </AppProvider>
  );
}
