import { useQuery } from '@apollo/client';
import { Shoe } from '@prisma/client';
import Head from 'next/head';
import Layout from '../components/layout';
import { AppProvider } from '../context/appContext';
import { GET_ALL_SHOES } from '../graphql/resolvers/queries';

export default function Home() {
  const { data, loading, error } = useQuery<{ getAllShoes: Shoe[] }>(GET_ALL_SHOES);
  if (data) {
    console.log(data);
  }

  return (
    <AppProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>
            <h1 className="text-3xl font-bold underline">
              {loading && <p>Loading...</p>}
              {error && <p>There was an error</p>}
              {data && <p>Data fetched - Check the console</p>}
            </h1>
          </div>
        </Layout>
      </main>
    </AppProvider>
  );
}
